GENRE_CHOICES = (
    ("Sports", ("Sports")),
    ("Platform", ("Platform")),
    ("Racing", ("Racing")),
    ("Role-Playing", ("Role-Playing")),
    ("Puzzle", ("Puzzle")),
    ("Misc", ("Misc")),
    ("Shooter", ("Shooter")),
    ("Simulation", ("Simulation")),
    ("Action", ("Action")),
    ("Fighting", ("Fighting")),
    ("Adventure", ("Adventure")),
    ("Strategy", ("Strategy"))
)

PLATFORM_CHOICES = (
    ("Wii", ("Wii")),
    ("NES", ("NES")),
    ("GB", ("GB")),
    ("DS", ("DS")),
    ("X360", ("X360")),
    ("PS3", ("PS3")),
    ("PS2", ("PS2")),
    ("SNES", ("SNES")),
    ("GBA", ("GBA")),
    ("PS4", ("PS4")),
    ("3DS", ("3DS")),
    ("N64", ("N64")),
    ("PS", ("PS")),
    ("XB", ("XB")),
    ("PC", ("PC")),
    ("2600", ("2600")),
    ("PSP", ("PSP")),
    ("XOne", ("XOne")),
    ("WiiU", ("WiiU")),
    ("GC", ("GC")),
    ("GEN", ("GEN")),
    ("DC", ("DC")),
    ("PSV", ("PSV")),
    ("SAT", ("SAT")),
    ("SCD", ("SCD")),
    ("WS", ("WS")),
    ("NG", ("NG")),
    ("TG16", ("TG16")),
    ("3DO", ("3DO")),
    ("GG", ("GG")),
    ("PCFX", ("PCFX"))
)
