GENRE_CHOICES = (
    (1, ("Sports")),
    (2, ("Platform")),
    (3, ("Racing")),
    (4, ("Role-Playing")),
    (5, ("Puzzle")),
    (6, ("Misc")),
    (7, ("Shooter")),
    (8, ("Simulation")),
    (9, ("Action")),
    (10, ("Fighting")),
    (11, ("Adventure")),
    (12, ("Strategy"))
)

PLATFORM_CHOICES = (
    (1, ("Wii")),
    (2, ("NES")),
    (3, ("GB")),
    (4, ("DS")),
    (5, ("X360")),
    (6, ("PS3")),
    (7, ("PS2")),
    (8, ("SNES")),
    (9, ("GBA")),
    (10, ("PS4")),
    (11, ("3DS")),
    (12, ("N64")),
    (13, ("PS")),
    (14, ("XB")),
    (15, ("PC")),
    (16, ("2600")),
    (17, ("PSP")),
    (18, ("XOne")),
    (19, ("WiiU")),
    (20, ("GC")),
    (21, ("GEN")),
    (22, ("DC")),
    (23, ("PSV")),
    (24, ("SAT")),
    (25, ("SCD")),
    (26, ("WS")),
    (27, ("NG")),
    (28, ("TG16")),
    (29, ("3DO")),
    (30, ("GG")),
    (31, ("PCFX"))
)
